# Generated by Django 5.2.8 on 2025-11-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_link_description'),
        ('users', '0003_user_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Products assigned to the user (for Staff/Connector).', to='links.product'),
        ),
    ]
