# Generated by Django 5.2.8 on 2025-11-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='The banner image.', upload_to='homepage_sliders/')),
                ('caption', models.CharField(blank=True, help_text='Optional text to display.', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (lowest first).')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this slide without deleting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Slider',
                'verbose_name_plural': 'Homepage Sliders',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
