# Generated by Django 5.2.8 on 2025-11-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pan', models.CharField(help_text='Customer PAN number (Unique identifier)', max_length=10, unique=True)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Admin can manually add commission for the referring Staff/Connector.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
