# Generated by Django 5.2.8 on 2025-11-17 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('links', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='referred_by',
            field=models.ForeignKey(help_text='The Staff/Connector who shared the unique link.', limit_choices_to={'role__in': ['STAFF', 'CONNECTOR']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.User'),
        ),
        migrations.AddField(
            model_name='customer',
            name='referred_for_product',
            field=models.ForeignKey(help_text='The bank product the customer was referred for.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='links.link'),
        ),
        migrations.CreateModel(
            name='ConnectorCommissionDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Connector Commission Summary',
                'verbose_name_plural': 'Connector Commission Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('customers.customer',),
        ),
    ]
