# Generated by Django 5.2.8 on 2025-11-17 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='referred_by',
            field=models.ForeignKey(help_text='The Staff/Connector who shared the unique link.', limit_choices_to={'role__in': ['STAFF', 'CONNECTOR']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
