# Generated by Django 5.2.8 on 2025-11-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, help_text='Additional notes or description about the customer.', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In Progress')], default='IN_PROGRESS', help_text="Current status of the customer's application.", max_length=20),
        ),
    ]
