# Generated by Django 5.2.8 on 2025-11-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pan',
            field=models.CharField(help_text='Customer PAN number (Unique identifier)', max_length=15, unique=True),
        ),
    ]
