# links/admin.py
from django.contrib import admin
from .models import Bank, Product, Link

# --- 1. Bank Admin ---
@admin.register(Bank)
class BankAdmin(admin.ModelAdmin):
    list_display = ('name', 'id')
    search_fields = ('name',)

# --- 2. Product Admin ---
@admin.register(Product)
class ProductAdmin(admin.ModelAdmin):
    list_display = ('name', 'id')
    search_fields = ('name',)

# --- 3. Link Admin (Updated) ---
@admin.register(Link)
class LinkAdmin(admin.ModelAdmin):
    list_display = (
        'name', 
        'bank', 
        'product', 
        'utm_link', 
        'id'
    )
    
    list_filter = ('bank', 'product')
    search_fields = ('name', 'bank__name', 'product__name')
    
    # Fields displayed in the Add/Edit form
    fieldsets = (
        ('Link Identification', {
            'fields': ('bank', 'product', 'name'),
            'description': 'Select the Bank and Product type for this link.',
        }),
        ('URL & Credentials', {
            'fields': ('utm_link', 'user_id', 'password', 'image'),
        }),
        ('Tracking URL', {
            'fields': ('internal_customer_onboarding_url',),
            'description': 'This is the internal URL pattern used for customer tracking.'
        }),
    )
    
    # The internal URL is read-only as it's generated by the model's save method
    readonly_fields = ('internal_customer_onboarding_url',)