# Generated by Django 5.2.8 on 2025-11-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_link_unique_together_link_unique_bank_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the link/campaign', null=True),
        ),
    ]
