# Generated by Django 5.2.8 on 2025-11-17 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='bank_logos/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Specific campaign name (e.g., 'HDFC Personal Loan 2024 Offer')", max_length=150)),
                ('utm_link', models.URLField(help_text='The final destination/UTM link for the bank')),
                ('user_id', models.CharField(blank=True, help_text='Optional bank portal User ID', max_length=100, null=True)),
                ('password', models.CharField(blank=True, help_text='Optional bank portal Password', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, help_text='Product image/logo', null=True, upload_to='link_images/')),
                ('internal_customer_onboarding_url', models.CharField(editable=False, help_text='Internal URL pattern: /onboard/<link_id>/<user_id>/', max_length=255)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.bank')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.product')),
            ],
            options={
                'unique_together': {('bank', 'product')},
            },
        ),
    ]
